apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: fibokubernetes-page-tls
spec:
  secretName: fibokubernetes-page
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fibokubernetes.page
  dnsNames:
    - fibokubernetes.page
    - www.fibokubernetes.page
  acme:
    solvers:
      - http01:
          ingressClass: nginx
        domains:
          - fibokubernetes.page
          - www.fibokubernetes.page
